import { Atom, Beaker, FlaskConical, Zap } from "lucide-react";

export const substances = [
  {
    id: "water",
    name: "Water",
    Hvap: 40.7,
    category: "common",
    color: "from-blue-400 to-cyan-400",
  },
  {
    id: "ethanol",
    name: "Ethanol",
    Hvap: 38.56,
    category: "common",
    color: "from-amber-400 to-orange-400",
  },
  {
    id: "methanol",
    name: "Methanol",
    Hvap: 35.3,
    category: "common",
    color: "from-green-400 to-emerald-400",
  },
  {
    id: "acetone",
    name: "Acetone",
    Hvap: 29.1,
    category: "common",
    color: "from-purple-400 to-pink-400",
  },
  {
    id: "benzene",
    name: "Benzene",
    Hvap: 30.8,
    category: "organic",
    color: "from-yellow-400 to-amber-400",
  },
  {
    id: "toluene",
    name: "Toluene",
    Hvap: 38.0,
    category: "organic",
    color: "from-orange-400 to-red-400",
  },
  {
    id: "chloroform",
    name: "Chloroform",
    Hvap: 29.2,
    category: "organic",
    color: "from-teal-400 to-green-400",
  },
  {
    id: "diethyl_ether",
    name: "Diethyl Ether",
    Hvap: 26.3,
    category: "organic",
    color: "from-indigo-400 to-purple-400",
  },
  {
    id: "hexane",
    name: "Hexane",
    Hvap: 28.9,
    category: "organic",
    color: "from-gray-400 to-blue-400",
  },
  {
    id: "heptane",
    name: "Heptane",
    Hvap: 31.1,
    category: "organic",
    color: "from-slate-400 to-gray-400",
  },
  {
    id: "carbon_tetrachloride",
    name: "Carbon Tetrachloride",
    Hvap: 29.9,
    category: "organic",
    color: "from-zinc-400 to-slate-400",
  },
  {
    id: "cyclohexane",
    name: "Cyclohexane",
    Hvap: 33.9,
    category: "organic",
    color: "from-neutral-400 to-zinc-400",
  },
  {
    id: "isopropanol",
    name: "Isopropanol",
    Hvap: 44.0,
    category: "common",
    color: "from-rose-400 to-pink-400",
  },
  {
    id: "acetaldehyde",
    name: "Acetaldehyde",
    Hvap: 31.3,
    category: "organic",
    color: "from-fuchsia-400 to-purple-400",
  },
  {
    id: "formaldehyde",
    name: "Formaldehyde",
    Hvap: 32.0,
    category: "organic",
    color: "from-violet-400 to-indigo-400",
  },
  {
    id: "ammonia",
    name: "Ammonia",
    Hvap: 23.4,
    category: "inorganic",
    color: "from-sky-400 to-blue-400",
  },
  {
    id: "hydrogen_peroxide",
    name: "Hydrogen Peroxide",
    Hvap: 41.0,
    category: "inorganic",
    color: "from-cyan-400 to-teal-400",
  },
  {
    id: "glycerol",
    name: "Glycerol",
    Hvap: 85.0,
    category: "organic",
    color: "from-emerald-400 to-green-400",
  },
  {
    id: "acetic_acid",
    name: "Acetic Acid",
    Hvap: 21.0,
    category: "organic",
    color: "from-lime-400 to-green-400",
  },
  {
    id: "nitromethane",
    name: "Nitromethane",
    Hvap: 27.2,
    category: "organic",
    color: "from-red-400 to-orange-400",
  },
  {
    id: "dimethyl_sulfoxide",
    name: "Dimethyl Sulfoxide (DMSO)",
    Hvap: 38.1,
    category: "organic",
    color: "from-amber-400 to-yellow-400",
  },
  {
    id: "pyridine",
    name: "Pyridine",
    Hvap: 34.0,
    category: "organic",
    color: "from-purple-400 to-fuchsia-400",
  },
  {
    id: "formic_acid",
    name: "Formic Acid",
    Hvap: 16.0,
    category: "organic",
    color: "from-pink-400 to-rose-400",
  },
  {
    id: "hydrazine",
    name: "Hydrazine",
    Hvap: 37.0,
    category: "inorganic",
    color: "from-blue-400 to-indigo-400",
  },
  {
    id: "hydrogen",
    name: "Hydrogen",
    Hvap: 0.9,
    category: "gas",
    color: "from-gray-300 to-blue-300",
  },
  {
    id: "oxygen",
    name: "Oxygen",
    Hvap: 6.8,
    category: "gas",
    color: "from-blue-300 to-cyan-300",
  },
  {
    id: "nitrogen",
    name: "Nitrogen",
    Hvap: 5.6,
    category: "gas",
    color: "from-purple-300 to-indigo-300",
  },
  {
    id: "carbon_dioxide",
    name: "Carbon Dioxide",
    Hvap: 8.0,
    category: "gas",
    color: "from-gray-400 to-slate-400",
  },
  {
    id: "sulfur_dioxide",
    name: "Sulfur Dioxide",
    Hvap: 10.5,
    category: "inorganic",
    color: "from-yellow-300 to-amber-300",
  },
];

export const categoryIcons = {
  common: Beaker,
  organic: FlaskConical,
  inorganic: Atom,
  gas: Zap,
};

export const categoryColors = {
  common: "border-blue-200 bg-blue-50 text-blue-700",
  organic: "border-green-200 bg-green-50 text-green-700",
  inorganic: "border-purple-200 bg-purple-50 text-purple-700",
  gas: "border-orange-200 bg-orange-50 text-orange-700",
};
